### ISSUE TITLE
material base color not changing in scenery editor

### ISSUE THREAD

**Issue by hasanofke** [ronh991/glTF-Blender-IO-MSFS#11]
### Current Behavior

![Microsoft Flight Simulator Screenshot 2024 03 05 - 13 13 06 01](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/143963739/d2a09744-9541-4823-b29c-38e95d1a13b4)
As seen in this image, when MSFS Material Params Standard is selected, if the base colour is changed, this is not reflected correctly in MSFS and shows the default texture colour.  

### Expected Behavior

When MSFS Material Params is selected, if the base colour changes, even if the colour of the texture is different, it should change in MSFS as in Blender. In the image above, the white corrugate coating was actually set to black.

### Steps To Reproduce

Since I was getting export errors in older versions, I tried it in different Blend files in Blender 4.0 and 4.2 and it was not solved.

### Environment

```markdown
- OS: Windows 11
- Blender: 4.0
- glTF-Blender-IO-MSFS: v2.2.0.2306
- MSFS: Sim Update 15 Beta
- MSFS SDK: 24.0 and 23.1 tested
```

**Comment by ronh991** [comment]
can you show me how it looks in blender - as I don't know what to look for

**Comment by hasanofke** [comment]
Yes, It does not detect when I copy the materials and change only the base colour. However, this problem occurs if I add an texture. I cannot adjust the colour of the textures with the help of base colour.
![Screenshot 2024-03-07 010325](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/143963739/d4e650b3-09dc-4a53-a17d-8f17bcef7b6e)
I am currently using the plugin you shared for Blender 3.6.9 in a different project.  Thanks.

**Comment by ronh991** [comment]
ok thank you for the clarification.  Your object/building is a light texture and it looks like you wish to darken it by adding a dark base color - this should work.  I will review to see what is not working as expected. I will look at the Blender 3.6 exporter

**Comment by hasanofke** [comment]
I am currently using 3.6.9 to avoid this problem. the problem only exists with the plugin you released for version 4.0.

**Comment by ronh991** [comment]
ok thank you for the report.

**Comment by ronh991** [comment]
A prerelease for B4.2 exporter ver 2.0.2.5 is in the release area, if you care to test.

**Comment by hasanofke** [comment]
thanks. I previously imported the building in 3.6.9, but now I imported it again from version 2.0.2.5 that you released for blender 4.0. it works correctly. I will still use it in 3.6.9 for now, but I will continue my tests and if I find any errors, I will definitely report them. thanks for your efforts. 

before vs after :)
![Microsoft Flight Simulator Screenshot 2024 03 08 - 00 44 19 02](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/143963739/8bce7233-336d-4dfb-9f86-6e792d2c3a63)

**Comment by hasanofke** [comment]
![Desktop Screenshot 2024 03 09 - 00 00 28 22](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/143963739/2c5e7326-16bd-44af-b239-c06e6d76196d)
also 4.0 addon is not working with Cycles render(if MSFS material is selected). is there a solution for this?

**Comment by ronh991** [comment]
Are you talking about the purple/pink texturing? I am working on this issue, however cycles rendering is not working and I do not know why.  EVEE does work.

The work around for the pink textures is to delete the color attribute and live with the nag button to apply vertex colors.

**Comment by ronh991** [comment]
Assume working now
