### ISSUE TITLE
Issue with the Vertex Color - forced use is causing issues in Render and Sim

### ISSUE THREAD

**Issue by ronh991** [ronh991/glTF-Blender-IO-MSFS#12]
### Current Behavior

The existing add-on forces the use of Vertex Color and Vertex color nodes.  Remove the forced requirement

### Expected Behavior

Allow the user to select if they choose to use the Vertex color nodes.

### Steps To Reproduce

ver 2.0.2.5 Blender 4.0+

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS:
NA
```

**Comment by hasanofke** [comment]
![Screenshot 2024-03-11 105159](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/143963739/41c111c2-071b-472f-a7f4-9b9511939506)
Hi, when something like this appears, I press the Apply button. How to use "Remove the forced requirement"?

**Comment by ronh991** [comment]
Applied the Addon preferences
