### ISSUE TITLE
vertex color node visualizer disconnect when assign texture

### ISSUE THREAD

**Issue by PGSimulation** [ronh991/glTF-Blender-IO-MSFS#13]
### Current Behavior

Clean Standard material without textures
![blender_UfjEPLFC19](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/a4238dc4-34f5-4edd-a116-ce6901418b5d)

When texture assign to base color dissconnect Vertec Base Color Multiply node 
![blender_hrYxwQP0Ki](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/ba07137f-d2cd-4bf8-9d03-7a73046bef3b)

Automatically adds Col vertex color but if select any color in Vertex Paint you can't see it in EEVEE
![obraz](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/c173bd8b-dd43-4495-bca2-f8d496ebf198)

This opion is checked
![obraz](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/b014dba4-98f8-4931-bf24-4166ef3e5484)

And 
![obraz](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/d4974a04-ced3-465a-acc5-64f08a452722)
if this option is changed despite forcing connect node with vertex color if texture is added will disconnect node and back to previous pic2 from pic1

### Expected Behavior

as in the first picture in Current Behavior
Vertex color connect to BaseColor PrinciplesBSDF to visualize 
![blender_UfjEPLFC19](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/61b27fb2-916d-40d2-bb59-df9835c5f5e1)

And a small request if it is possible to automatically add "Face Corner Color" instead of "Face Corner Byte Color". This change eliminates rainbow object bug if more than 1 material is assigned to an object. 
Tested on multiple sceneries and works fine
![blender_A0w4kKBRlA](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/ea67dea0-3be2-4e09-b39b-5f4bd14abcad)
![blender_GdoWApyIJR](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/b87f1f75-8872-4e7f-9bad-ac2cf1e82cb2)

### Steps To Reproduce

1. Add plane object
2. Assign Standard MSFS Material
3. Assign BAse Color texture
4. Go to Vertex Paint
5. Add any color
6. Enable Viewport Shading. | you will not see vertex color
7. connect the Vertex Color Mul node back up to Base color in the shading tab | Texture object changes color with vertex color

### Environment

```markdown
- OS: Windows 10
- Blender: 3.6.9 LTS
- glTF-Blender-IO-MSFS: 3.6-Update | 08.04.2024 | f283a95 - Synch to ASOBO 1.3.3 and add my changes
```

### Anything else?

If the object does not have any textures again add a button to assign vertex color attribute. 
it was in some older versions of this add-on

**Comment by ronh991** [comment]
I will look into this.  As to the Face Corner Color issue.  This is a core Blender Khronos setup.  I have hook in the code that changes this during the export process.  I'll review this

**Comment by ronh991** [comment]
If you can could you test this update?

removed - new link coming

**Comment by ronh991** [comment]
Newer update - Please test

added base color - button to apply vertex color
bug fixes

1.6.3.2

[io_scene_gltf2_msfs_for36.zip](https://github.com/ronh991/glTF-Blender-IO-MSFS/files/15013151/io_scene_gltf2_msfs_for36.zip)

**Comment by PGSimulation** [comment]
> If you can could you test this update?

is slightly bugged at the moment because if i doesn't manually assign vertex color himself before select standard material in addon

Then it does not plug in vertex color multiply node at all either without texture or with texture. 
and it does not add col vertex color attribute in both cases

But if I go into preferences uncheck and check again this option
![blender_lB3Pi3XtFH](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/78fe433f-ab09-4fad-b657-77cecb69ac48)
node works correctly and also adds vertex color after assigning a texture 
then even after restarting blender and reopen saved project it works

but if even without reopen blender but open / create new Blend File. New, General project again does not work 

so I think it's strongly related to the newly added button in preferences and for some reason it doesn't load it correctly until you uncheck it and select it and save the state in the blend file 

EDIT:
message refers to previous version deleted

**Comment by PGSimulation** [comment]
> Newer update - Please test
> 
> added base color - button to apply vertex color bug fixes
> 
> 1.6.3.2
> 
> [io_scene_gltf2_msfs_for36.zip](https://github.com/ronh991/glTF-Blender-IO-MSFS/files/15013151/io_scene_gltf2_msfs_for36.zip)

same problem everything works if you uncheck and select the button and save the blend file. for some reason when you open a clean project it doesn't automatically take into account that the checkbox is selected

**Comment by PGSimulation** [comment]
If I saved the startup project file after this action the same works correctly

**Comment by ronh991** [comment]
ah ok, thanks for reporting.

**Comment by ronh991** [comment]
New update - please test 1.6.3.3
[io_scene_gltf2_msfs_for36.zip](https://github.com/ronh991/glTF-Blender-IO-MSFS/files/15016846/io_scene_gltf2_msfs_for36.zip)

**Comment by PGSimulation** [comment]
works. thank you for the quick fix 

one more small note by default metallic is on 1 instead of 0 with models without pbr it theoretically matters but you can change it manually

**Comment by ronh991** [comment]
Default metallic for what material - Standard only?
Not sure I understand.  "without PBR" they are all PBR materials

**Comment by PGSimulation** [comment]
> Default metallic for what material - Standard only? Not sure I understand. "without PBR" they are all PBR materials

Not very significant because if the material has textures then this slider does not affect anything and should be on 1

but if the material of any kind, such as standard under the LOD of the model without textures then 1 for metallic means metal and so it displays in msfs and blender viewport so theoretically for 99% of cases it should default to 0 and only after adding a texture set to 1

**Comment by ronh991** [comment]
Ok I understand now.  However,  I will not be able to do that because I would like to keep the exporter as close as possible to ASOBO, I don't like it, where code changes an unrelated value, if you change a texture the metallic factor changes.

You could modify your own version to set the default metallic_factor to 0.0

**Comment by ronh991** [comment]
should be fixed
