### ISSUE TITLE
Error when trying to export: use_unique_id

### ISSUE THREAD

**Issue by Tisor** [ronh991/glTF-Blender-IO-MSFS#14]
### Current Behavior

When trying to export any project from Blender 4.2, I get the following error:

[Blender 4.2 LTS Alpha - Pre Release Development](https://github.com/ronh991/glTF-Blender-IO-MSFS/releases/tag/v2.2.1.2)

`Error: Python: Traceback (most recent call last):
  File "C:\Users\Dani\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 299, in execute
    MSFS_OT_MultiExportGLTF2.export(exportPath)
  File "C:\Users\Dani\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 202, in export
    bpy.context.scene.msfs_exporter_settings.use_unique_id = settings.use_unique_id
                                                             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'addSettingsPanel' object has no attribute 'use_unique_id'
`

Already tried install

### Expected Behavior

Export an object with no errors.

### Steps To Reproduce

1. Open any project in Blender 4.2
2. Set up the exporter
3. Export
4. No export: error will show

### Environment

```markdown
- OS: Windows 11
- Blender: 4.2.0 Alpha
- glTF-Blender-IO-MSFS: Blender 4.2 LTS Alpha - Pre Release Development
```

**Comment by ronh991** [comment]
The latest 4.2 alpha has completely messed up the exporter.  try going back to April 24th version.

**Comment by ronh991** [comment]
ok working on a fix

**Comment by ronh991** [comment]
blender/Khronos issue
https://github.com/KhronosGroup/glTF-Blender-IO/issues/2253

**Comment by ronh991** [comment]
should be fixed

**Comment by 4lexcha** [comment]
Same error when exporting. I'm using Blender 3.6.11 (portable) with 1.6.8 addon. Clean start, simple model (plain surface with one material, no textures).
![image](https://github.com/user-attachments/assets/c41c282c-3391-4d75-8b05-d959a74473b5)

**Comment by ronh991** [comment]
thanks for the report - please try this

**Comment by ronh991** [comment]
no that did not work, sorry

**Comment by ronh991** [comment]
please try this
[io_scene_gltf2_msfs_for36.zip](https://github.com/user-attachments/files/16661386/io_scene_gltf2_msfs_for36.zip)

**Comment by 4lexcha** [comment]
> please try this [io_scene_gltf2_msfs_for36.zip](https://github.com/user-attachments/files/16661386/io_scene_gltf2_msfs_for36.zip)

thanks. it's working without errors
