### ISSUE TITLE
version above 16 december 2023 for blender 3.6 not export emission day night cycle extension

### ISSUE THREAD

**Issue by PGSimulation** [ronh991/glTF-Blender-IO-MSFS#8]
### Current Behavior

```py
	],
	"materials":[
		{
			"emissiveFactor":[
				0.5,
				0.5,
				0.5
			],
			"emissiveTexture":{
				"index":0
			},
			"name":"MaterialName",
			"normalTexture":{
				"index":1
			},
			"occlusionTexture":{
				"index":2
			},
			"pbrMetallicRoughness":{
				"baseColorTexture":{
					"index":3
				},
				"metallicRoughnessTexture":{
					"index":2
				}
			}
		}
	],
```

### Expected Behavior

```py
	"materials":[
		{
			"emissiveFactor":[
				1,
				1,
				1
			],
			"emissiveTexture":{
				"index":0
			},
			"extensions":{
				"ASOBO_material_day_night_switch":{}
			},
			"extras":{},
			"name":"MaterialName",
			"normalTexture":{
				"index":1
			},
			"occlusionTexture":{
				"index":2
			},
			"pbrMetallicRoughness":{
				"baseColorFactor":[
					1,
					1,
					1,
					1
				],
				"baseColorTexture":{
					"index":3
				},
				"metallicRoughnessTexture":{
					"index":2
				}
			}
		}
	],
```

### Steps To Reproduce

checkout commit from 16 december 2023 in git app for blender 3.6 branch and try export material with standard shader with emission pbr map, color 1.0 and day night cycle. and then checkout commit from 20 december or newer and export the same material. 
```py
			"extensions":{
				"ASOBO_material_day_night_switch":{}
			},
			"extras":{},
```
Dissapear and day night cycle for emission not working 
![obraz](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/815df303-61f2-4141-b577-b58af196cc79)
![obraz](https://github.com/ronh991/glTF-Blender-IO-MSFS/assets/32337512/2bf4858e-e005-45f1-81d4-f62f673262b0)

### Environment

```markdown
- OS: Windows 10
- Blender: 3.6.5
- glTF-Blender-IO-MSFS: 
Working: 1, 6, 2, 17 aef555a - Update for BaseColor deleted if BaseColor texture
Not Working version or above: 1, 6, 2, 181299bf9 - Bug fix BaseColor checks
```

**Comment by ronh991** [comment]
Thank you for your report.  How are you getting my code for use?  Do you need a io_scene_gltf2_msfs.zip file or are you downloading my git project?
[io_scene_gltf2_msfs_for36.zip](https://github.com/ronh991/glTF-Blender-IO-MSFS/files/13835602/io_scene_gltf2_msfs_for36.zip)

**Comment by PGSimulation** [comment]
> Thank you for your report. How are you getting my code for use? Do you need a io_scene_gltf2_msfs.zip file or are you downloading my git project? [io_scene_gltf2_msfs_for36.zip](https://github.com/ronh991/glTF-Blender-IO-MSFS/files/13835602/io_scene_gltf2_msfs_for36.zip)

I download a specific commit from the "Fork" app but also sometimes the latest from branch 3.6 from the github site as a zip
As newest zip: https://github.com/ronh991/glTF-Blender-IO-MSFS/tree/3.6-Update
Or: https://github.com/ronh991/glTF-Blender-IO-MSFS/tree/aef555ab090de3ea04adb31dd94b0799f4716f7e

**Comment by ronh991** [comment]
I would appreciate if you could test and report back if I have fixed this issue.  So I can push this fix to 4.0 Update

**Comment by PGSimulation** [comment]
> I would appreciate if you could test and report back if I have fixed this issue. So I can push this fix to 4.0 Update

Yes. ae41dbe works properly.

**Comment by ronh991** [comment]
Issue has been resolved - closing

**Comment by coldrifting** [comment]
This issue seems to have reoccurred in the latest version for both blender versions 4.2 and 4.5. Chaing the line ```name=AsoboDayNightCycle.SerializedName, extension={'dummy': None} , required=False```  in the ```com\msfs_material_props.py``` file to ```name=AsoboDayNightCycle.SerializedName, extension={'enabled': True} , required=False``` seems to fix the issue.
